server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:oracle:thin:@3.36.218.186:1522/xe
    #url: jdbc:oracle:thin:@192.168.0.10:1522/xe
    url: jdbc:mysql://localhost:3306/healingdog?useSSL=false&
    username: healingdog
    password: healingdog
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/healingimgs/
  profiles:
    include: security

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # configuration/WebConfig.java
  add-resource-handler: /healingimgs/**
  add-resource-locations: C:/edu/file/healingimgs/

  # **Service.java
  image-directory-prefix: /healingimgs/
  # AWS EC2 등록 시 필요한 prefix
  # image-url-prefix: http://3.36.218.186:8090/healingimgs/
  image-url-prefix: http://localhost:8090/healingimgs/

  type:
    member: member/
    service: service/
    review: review/
    board: board/
    certificate: certificate/

page:
  show-list-amount: 10
  show-page-amount: 10

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
# jwt 설정은 application-security.yml 파일에서 적용 - line 21

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.healing.healingdog
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
#어느 로그 단계 이상부터 출력할 것인지 설정, 예)info 기입 시 trace를 제외한 모든 로그 출력.
#(가장 낮음) trace, info, debug, warn, error (가장 높음)

